class SupabaseConfig {
  static const String supabaseUrl = 'https://weagjqbymxgewtdpvagy.supabase.co';
  static const String supabaseAnonKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYWdqcWJ5bXhnZXd0ZHB2YWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzY3MDAsImV4cCI6MjA3MzY1MjcwMH0.tcySPavw729fMlxSOShdvLbcfSQJWjQnOd0lFa01dzE';
  static const String supabaseServiceRoleKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYWdqcWJ5bXhnZXd0ZHB2YWd5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODA3NjcwMCwiZXhwIjoyMDczNjUyNzAwfQ.jyswSQkEse-PfqjuD9yVIyxeRitLse4gnGaYMk_4r6c';
}
